/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.newdeal.lms;

import java.sql.Date;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
      Scanner keyIn = new Scanner(System.in);
      
      System.out.print("번호?");
      int no = Integer.parseInt(keyIn.nextLine());
      
      System.out.print("이름?");
      String name = keyIn.nextLine();
      
      System.out.print("이메일?");
      String email = keyIn.nextLine();
      
      System.out.print("암호?");
      int password = Integer.parseInt(keyIn.nextLine());
      
      System.out.print("사진?");
      String p = keyIn.nextLine();
      
      System.out.print("전화?");
      String pn = keyIn.nextLine();
      
      keyIn.close();
      
      System.out.println("번호: %s%n"+no);
      System.out.println("이름: %s%n"+name);
      System.out.println("이메일: %s%n"+email);
      System.out.println("암호: %s%n"+password);
      System.out.println("사진: %s%n"+p);
      System.out.println("전화: %s%n"+pn);
      
    }
}
