/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.newdeal.lms;

import java.util.Date;
import java.util.Scanner;

public class App2 {
    public static void main(String[] args) {
      Scanner keyIn = new Scanner(System.in);
      
      Date date;
      
      System.out.print("번호?");
      int no = Integer.parseInt(keyIn.nextLine());
      
      System.out.print("이름?");
      String name = keyIn.nextLine();
      
      System.out.print("이메일?");
      String email = keyIn.nextLine();
      
      System.out.print("암호?");
      int password = Integer.parseInt(keyIn.nextLine());
      
      System.out.print("사진?");
      String p = keyIn.nextLine();
      
      System.out.print("전화?");
      String pn = keyIn.nextLine();
      
      date = new Date();      
      
      keyIn.close();
      
      System.out.printf("번호: %s%n",no);
      System.out.printf("이름: %s%n",name);
      System.out.printf("이메일: %s%n",email);
      System.out.printf("암호: %s%n",password);
      System.out.printf("사진: %s%n",p);
      System.out.printf("전화: %s%n",pn);
      System.out.printf("가입일: %s%n",date);
      
    }
}
