/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.newdeal.lms;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {
      System.out.printf("숫자를 입력하시오");
      Test t = new Test();
      Scanner sc = new Scanner(System.in);
      int num = sc.nextInt(); 
      t.input(num);
    }
}
