/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitcamp.newdeal.lms;

import java.sql.Date;
import java.util.Scanner;

public class App4 {
    public static void main(String[] args) {
      
      final int DEFAULT_SIZE = 20;
      
      int[] no = new int[DEFAULT_SIZE];
      String[] title = new String[DEFAULT_SIZE];
      String[] contents = new String[DEFAULT_SIZE];
      Date[] startDate = new Date[DEFAULT_SIZE];
      Date[] endDate = new Date[DEFAULT_SIZE];
      int[] totalHours = new int[DEFAULT_SIZE];
      int[] dayHours = new int[DEFAULT_SIZE];
      
      int len = 0;
      
      Scanner keyIn = new Scanner(System.in);

      for(i=0;i<DEFAULT_SIZE;i++, len++) {
        System.out.print("번호?");
        no = Integer.parseInt(keyIn.nextLine());
        
        System.out.print("이름?");
        String name = keyIn.nextLine();
        
        System.out.print("이메일?");
        String email = keyIn.nextLine();
        
        System.out.print("암호?");
        int password = Integer.parseInt(keyIn.nextLine());
        
        System.out.print("사진?");
        String p = keyIn.nextLine();
        
        System.out.print("전화?");
        String pn = keyIn.nextLine();
      }
      keyIn.close();
      
      System.out.println("번호: %s%n"+no);
      System.out.println("이름: %s%n"+name);
      System.out.println("이메일: %s%n"+email);
      System.out.println("암호: %s%n"+password);
      System.out.println("사진: %s%n"+p);
      System.out.println("전화: %s%n"+pn);
      
    }
}
